[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "23"
android-targetSdk = "36"
androidx-activityCompose = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-lifecycle = "2.9.4"
# As per https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-navigation-routing.html
installreferrer = "2.2"
libphonenumber-android = "9.0.16"
libphonenumber-google = "9.0.16"
navigation = "2.9.0"
argparse4j = "0.9.0"
compose-multiplatform = "1.9.0"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.4"
kotlinx-coroutines = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktor = "3.3.0"
logback = "1.5.18"
json-schema-validator = "1.5.9"
uri-kmp = "0.0.20"
kotlinx-date-time = "0.7.1"
okhttp = "5.1.0"
jsoup = "1.21.2"
runner = "1.7.0"
core = "1.7.0"
koin = "4.1.1"
turbine = "1.2.1"
room = "2.8.2"
androidx-sqlite = "2.6.1"
coil3 = "3.3.0"
multiplatformsettings = "1.3.0"
koalaplot-version = "0.6.4"
androidx-webkit = "1.14.0"
kotlinx-io = "0.8.0"
nanohttpd =  "2.3.1"
napier = "2.7.1"
mockwebserver =  "5.1.0"
mockito-kotlin =  "6.0.0"
androidx-credentials =  "1.5.0"
androidx-work = "2.10.4"
jvm-toolchain = "17"
acra = "5.13.1"
kscan = "0.5.0"
accompanist-permissions = "0.37.3"
qrose = "1.0.1"

# Compose material3 as per https://developer.android.com/jetpack/androidx/releases/compose-material3
# Required to use material3 window sizes
compose-material3 = "1.3.2"
reorderable = "3.0.0"
lz4 = "1.8.0"
atomicfu = "0.29.0"
material = "1.13.0"

swagger-generator = "2.19.2"
swagger-codegen = "3.0.73" # As per https://swagger.io/docs/open-source-tools/swagger-codegen/codegen-v3/about/
swagger-ui = "5.28.1"

androidx-paging = "3.4.0-alpha04"
androidx-paging-compose = "3.4.0-alpha04" # Different as per https://developer.android.com/topic/libraries/architecture/paging/v3-overview
webauthn4j-core =  "0.25.0.RELEASE"

androidx-preference = "1.2.1"
androidx-biometric = "1.4.0-alpha02"
buildconfig-plugin = "6.0.6"

[libraries]
argparse4j = { module = "net.sourceforge.argparse4j:argparse4j", version.ref = "argparse4j" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
coil3-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil3" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
libphonenumber-google = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber-google" }
libphonenumber-android = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumber-android"}
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
multiplatformsettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformsettings"}
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator" }
ktor-client-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-conditional-headers = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-auto-head-response = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
compose-material3-window-size-clazz = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material3" }

androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidx-webkit" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
kotlinx-date-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-date-time" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }

koalaplot = {module = "io.github.koalaplot:koalaplot-core",version.ref = "koalaplot-version"}
kscan = { module = "io.github.ismai117:KScan", version.ref = "kscan" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging-compose" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite" }
lz4-pure-java = { module = "org.lz4:lz4-pure-java", version.ref = "lz4" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-io-okio = { module = "org.jetbrains.kotlinx:kotlinx-io-okio", version.ref = "kotlinx-io"}
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd"}
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver"}
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin"}
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle"}
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-service-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials" }
webauthn4j-core = { module="com.webauthn4j:webauthn4j-core", version.ref = "webauthn4j-core"}

androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometric" }
swagger-codegen-cli = { module = "io.swagger.codegen.v3:swagger-codegen-cli", version.ref = "swagger-codegen" }
swagger-ui = { module = "org.webjars:swagger-ui", version.ref = "swagger-ui" }

androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

acra-http = { module = "ch.acra:acra-http", version.ref = "acra" }
acra-core = { module = "ch.acra:acra-core", version.ref = "acra" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }




[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
swagger-generator = { id= "org.hidetake.swagger.generator", version.ref = "swagger-generator" }
buildconfigPlugin = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig-plugin"}